### ISSUE TITLE
Login Page with bootstrap

### ISSUE THREAD

**Issue by h4mit** [sina-thr/Exercise#1]
با کمک چارچوب bootstrap صفحه login بساز

@sina-thr :smile:

**Comment by sina-thr** [comment]
<!DOCTYPE html>
<html>
<body style="text-align:center">
    <h1>Login Page</h1>
    <form>
      Username:
      <input type="text" style="margin:10px"><br>
      Password:
      <input type="password"><br>
    </form>
</body>
</html>

**Comment by sina-thr** [comment]
عه چرا این شکلی شد؟؟

**Comment by h4mit** [comment]
:smile: in be payan resid
