### ISSUE TITLE
register page - bootstrap

### ISSUE THREAD

**Issue by h4mit** [sina-thr/Exercise#2]
Mesle login, Register ro besaz :blush: 

username
password
email 
terms -> popup | checkbox

:+1:

**Comment by sina-thr** [comment]
popup o natunestam :(((

**Comment by h4mit** [comment]
@sina-thr baraye add kardane Modal bayad 2 ta ketabkhone javascripti ro faal konim 

`
< script src="js/jquery.min.js"></ script>
< script src="js/bootstrap.min.js"></ script>
`

>  dar asl ma faghat bayad js/bootstrap.min.js ra faal konim ama khode in niaz be jquery dare :blush: :wink:
